[package]
name = "glide_compiler"
version = "0.1.0"
authors = ["Michael Oates <michael@oates.dev>"]
edition = "2018"

[features]
default = []
eval = []

[dependencies]
log={ version = "0.4.14" }
logos = "0.12.1"
instruction_set = { path = "../instruction_set" }
anyhow = "1.0.38"
itertools="0.10.5"
